name: ⚙️ Release on PGXN
on:
  push:
    # Release on semantic version tag.
    tags: ['v[0-9]+.[0-9]+.[0-9]+']
jobs:
  release:
    if: github.repository == 'tembo-io/pgmq'
    name: Release on PGXN
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    defaults:
      run:
        working-directory: ./pgmq-extension
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Bundle the Release
        run: make dist
      - name: Release on PGXN
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release
